/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pregrado
 */
public class BuscarGeneral extends javax.swing.JInternalFrame {
    static Toolkit t = Toolkit.getDefaultToolkit();
    static Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    MyModel4 modelo;
    MyModel5 modelo1;
    /**
     * Creates new form BuscarGeneral
     */
    public BuscarGeneral() {
        initComponents();
        this.setPreferredSize(new java.awt.Dimension((screenSize.width)*2/3, screenSize.height));
        PanelBuscar.setPreferredSize(new java.awt.Dimension(((screenSize.width)*2/3)-12, screenSize.height-31));
        CargarTablaBucar("NADA");
        CargarTablaJuntos("NADA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBuscar = new javax.swing.JPanel();
        campobuscador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablabuscar = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablajuntos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        campobuscador1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(540, 400));

        PanelBuscar.setBackground(new java.awt.Color(204, 204, 255));
        PanelBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 3, true));

        campobuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campobuscadorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("INGRESE TEXTO :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("BUSCAR POR ASOCIADO");

        tablabuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Placa", "Propietario", "Chofer", "Cobrador"
            }
        ));
        jScrollPane1.setViewportView(tablabuscar);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablajuntos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Placa", "Propietario", "Chofer", "Cobrador"
            }
        ));
        jScrollPane2.setViewportView(tablajuntos);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("INGRESE TEXTO :");

        campobuscador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campobuscador1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("BUSCAR POR VEHICULO");

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(PanelBuscarLayout.createSequentialGroup()
                                        .addComponent(campobuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelBuscarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(campobuscador1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(59, 59, 59))
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campobuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campobuscador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campobuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campobuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campobuscadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!campobuscador.getText().equals("")){
        campobuscador1.setText("");
        CargarTablaBucar(campobuscador.getText());
        if(tablabuscar.getRowCount()!=0){
        CargarTablaJuntos(tablabuscar.getValueAt(0,0).toString());
        }else{
            JOptionPane.showMessageDialog(this, "NO EXISTE ASOCIADO");
        }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campobuscador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campobuscador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campobuscador1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!campobuscador1.getText().equals("")){
        campobuscador.setText("");
        CargarTablaJuntos(campobuscador1.getText());
        if(tablajuntos.getRowCount()!=0){
        CargarTablaBucar(tablajuntos.getValueAt(0,3).toString());
        }else{
            JOptionPane.showMessageDialog(this, "NO EXISTE VEHICULO");
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    void CargarTablaBucar(String valor)
    {
        String[] titulos={"DNI","Nombres","Apellidos","Direccion","Distrito"};
        String[] registro=new String[5];
        modelo=new MyModel4(null,titulos);
        
            
                        //CargarTablaSalidas("");
                        ConexionOracle  Oracle=new ConexionOracle();
                        Oracle.Conectar();
                        String consultaOracle1="SELECT DNI_ASOCIADO,NOM_ASOCIADO,APE_ASOCIADO,DIR_ASOCIADO,DIS_ASOCIADO FROM ASOCIADOS "+
                                "WHERE DNI_ASOCIADO || ' ' || NOM_ASOCIADO || ' ' || APE_ASOCIADO || ' ' || DIR_ASOCIADO || ' ' || DIS_ASOCIADO LIKE '%"+valor+"%'";
                        try{
                        ResultSet rs=Oracle.getst().executeQuery(consultaOracle1);
                        
                        while(rs.next())
                        {
                            registro[0]=rs.getString("DNI_ASOCIADO");
                            registro[1]=rs.getString("NOM_ASOCIADO");
                            registro[2]=rs.getString("APE_ASOCIADO");
                            registro[3]=rs.getString("DIR_ASOCIADO");
                            registro[4]=rs.getString("DIS_ASOCIADO");
                            modelo.addRow(registro);
                        }
                        tablabuscar.setModel(modelo);
                        tablabuscar.getTableHeader().setReorderingAllowed(false);
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(this, "Error Ingresando Datos - Codigo : "+e);
                    }
    }
    
    void CargarTablaJuntos(String valor)
    {
        String[] titulos={"Placa","Modelo","Año","DNI Asociado","DNI Chofer","DNI Cobrador"};
        String[] registro=new String[6];
        modelo1=new MyModel5(null,titulos);
        
            
                        //CargarTablaSalidas("");
                        ConexionOracle  Oracle=new ConexionOracle();
                        Oracle.Conectar();
                        String consultaOracle1="SELECT PLACA_VEHICULO,MODELO_VEHICULO,ANIO_VEHICULO,DNI_ASOCIADO,DNI_CHOFER,DNI_COBRADOR FROM VEHICULOS "+
                                "WHERE PLACA_VEHICULO || ' ' || MODELO_VEHICULO || ' ' || ANIO_VEHICULO || ' ' || DNI_ASOCIADO || ' ' || DNI_CHOFER || ' ' || DNI_COBRADOR LIKE '%"+valor+"%'";
                        try{
                        ResultSet rs=Oracle.getst().executeQuery(consultaOracle1);
                        
                        while(rs.next())
                        {
                            registro[0]=rs.getString("PLACA_VEHICULO");
                            registro[1]=rs.getString("MODELO_VEHICULO");
                            registro[2]=rs.getString("ANIO_VEHICULO");
                            registro[3]=rs.getString("DNI_ASOCIADO");
                            registro[4]=rs.getString("DNI_CHOFER");
                            registro[5]=rs.getString("DNI_COBRADOR");
                            modelo1.addRow(registro);
                        }
                        tablajuntos.setModel(modelo1);
                        tablajuntos.getTableHeader().setReorderingAllowed(false);
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(this, "Error Ingresando Datos - Codigo : "+e);
                    }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JTextField campobuscador;
    private javax.swing.JTextField campobuscador1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablabuscar;
    private javax.swing.JTable tablajuntos;
    // End of variables declaration//GEN-END:variables
}


class MyModel4 extends DefaultTableModel 
{
   public MyModel4(Object[][] data, Object[] cols) 
   {
      super(data, cols);
   }

   public boolean isCellEditable(int row, int col) 
   {
      return false;
   }
}

class MyModel5 extends DefaultTableModel 
{
   public MyModel5(Object[][] data, Object[] cols) 
   {
      super(data, cols);
   }

   public boolean isCellEditable(int row, int col) 
   {
      return false;
   }
}