/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pregrado
 */
public class EditarAsociado extends javax.swing.JInternalFrame {
    static Toolkit t = Toolkit.getDefaultToolkit();
    static Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    MyModel1 modelo;
    int row=-1;
    String placa_vehi;
    String modelo_vehi;
    String anio_vehi;
    String dni_chofer;
    String dni_cobra;
    int numero;
    /**
     * Creates new form EditarAsociado
     */
    public EditarAsociado() {
        
        initComponents();
        this.setPreferredSize(new java.awt.Dimension((screenSize.width)*2/3, screenSize.height));
        PanelEditar.setPreferredSize(new java.awt.Dimension((screenSize.width)*2/3-12, screenSize.height-31));
        //campodni.setEnabled(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEditar = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablavehiculos = new javax.swing.JTable();
        campodireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campodni = new javax.swing.JTextField();
        campoapellido = new javax.swing.JTextField();
        camponombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BoxDistritos = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(540, 400));

        PanelEditar.setBackground(new java.awt.Color(204, 204, 255));
        PanelEditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 3, true));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Modificar Vehiculo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Eliminar Vehiculo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Agregar Vehiculo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablavehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Modelo", "Año"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablavehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablavehiculosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablavehiculos);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DIRECCION :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("NOMBRES :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("APELLIDOS :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DNI :");

        campodni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campodniActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("VEHICULOS DEL ASOCIADO");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("DISTRITO :");

        BoxDistritos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ancón", "Ate", "Barranco", "Breña", "Carabayllo", "Chaclacayo", "Chorrillos", "Cieneguilla", "Comas", "El Agustino", "Independencia", "Jesús María", "La Molina", "La Victoria", "Lince", "Los Olivos", "Lurigancho-Chosica", "Lurin", "-Magdalena del Mar", "Pueblo Libre", "Miraflores", "Pachacámac", "Pucusana", "Puente Piedra", "Punta Hermosa", "Punta Negra", "Rímac", "San Bartolo", "San Borja", "San Isidro", "San Juan de Lurigancho", "San Juan de Miraflores", "San Luis", "San Martín de Porres", "San Miguel", "Santa Anita", "Santa María del Mar", "Santa Rosa", "Santiago de Surco", "Surquillo", "Villa El Salvador", "Villa María del Triunfo" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("EDITAR ASOCIADOS");

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton4))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campodni)
                                .addComponent(camponombre)
                                .addComponent(campoapellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(campodireccion)
                                .addComponent(BoxDistritos, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5)))
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelEditarLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(42, 42, 42)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(215, 215, 215))
            .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                    .addContainerGap(311, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(262, 262, 262)))
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campodni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(camponombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campodireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxDistritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(45, 45, 45)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelEditarLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel6)
                    .addContainerGap(680, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
                        ConexionOracle  Oracle=new ConexionOracle();
                        Oracle.Conectar();
                        String consultaOracle = "UPDATE ASOCIADOS SET DIR_ASOCIADO = '"+campodireccion.getText()+
                                "',DIS_ASOCIADO = '"+BoxDistritos.getSelectedItem().toString()+"' WHERE DNI_ASOCIADO = '"+
                                campodni.getText()+"'";
                        //System.out.println(consultaOracle);
                        Oracle.getst().execute(consultaOracle);
                        Oracle.getConexion().close();
                        JOptionPane.showMessageDialog(this, "Asociado modificado correctamente");
                        this.setVisible(false);
                        
                        if(numero==1){
                            Inicio.f3.setVisible(true);
                            Inicio.f3.setnumero(1);
                            Inicio.f3.CargarTablaAsociados("");
                            
                        }
                        if(numero==2){
                            GestorAsociados.f3.setVisible(true);
                            GestorAsociados.f3.setnumero(2);
                            GestorAsociados.f3.CargarTablaAsociados("");
                            
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Error Ingresando Datos - Codigo : "+e);
                    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        if(numero==1){
            Inicio.f3.setVisible(true);
            Inicio.f3.setnumero(1);
        }
        if(numero==2){
            GestorAsociados.f3.setVisible(true);
            GestorAsociados.f3.setnumero(2);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(row==-1){
            JOptionPane.showMessageDialog(null, "Por favor seleccione un vehiculo");
        }else{
        this.setVisible(false);
        if(numero==1){
           Inicio.f8.setnumero(1);
           Inicio.f8.seter();
           Inicio.f8.setVisible(true); 
        }
        if(numero==2){
           GestorAsociados.f8.setnumero(2);
           GestorAsociados.f8.seter();
           GestorAsociados.f8.setVisible(true); 
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void campodniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campodniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campodniActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        row=tablavehiculos.getSelectedRow();
        String consultaOracle= "";
        String consultaOracle1= "";// SALIDAS
        String consultaOracle2= "";// SALIDAS
        String consultaOracle3= "";// SALIDAS
        String consultaOracle4= "";// SALIDAS
        //modelo=new MyModel(null,titulos);
        String primarykey=tablavehiculos.getValueAt(row, 0).toString();
        String primarykeyCHO=tablavehiculos.getValueAt(row, 3).toString();
        String primarykeyCO=tablavehiculos.getValueAt(row, 4).toString();
        ConexionOracle  Oracle=new ConexionOracle();
        Oracle.Conectar();
        //Connection cn=Oracle.Conectar();
        consultaOracle="DELETE FROM VEHICULOS WHERE PLACA_VEHICULO = '"+primarykey+"'"; 
        consultaOracle1="DELETE FROM CHOFERES WHERE DNI_CHOFER = '"+primarykeyCHO+"'";
        consultaOracle2="DELETE FROM COBRADORES WHERE DNI_COBRADOR = '"+primarykeyCO+"'";
        consultaOracle3="DELETE FROM SALIDAS WHERE PLACA_VEHICULO = '"+primarykey+"'"; 
        consultaOracle4="DELETE FROM QUEJAS WHERE PLACA_VEHICULO = '"+primarykey+"'"; 
        try{
            int resp = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar?","ELIMINAR VEHICULO", JOptionPane.YES_NO_OPTION);
              if(resp==JOptionPane.YES_OPTION){
                ResultSet rs=Oracle.getst().executeQuery(consultaOracle);
                ResultSet rs1=Oracle.getst().executeQuery(consultaOracle1);
                ResultSet rs2=Oracle.getst().executeQuery(consultaOracle2);
                ResultSet rs3=Oracle.getst().executeQuery(consultaOracle3);
                ResultSet rs4=Oracle.getst().executeQuery(consultaOracle4);
                CargarTablaVehiculos("");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        if(numero==1){
            Inicio.f9.setnumero(1);
            Inicio.f9.vaciar();
            Inicio.f9.setVisible(true);
        }
        if(numero==2){
            GestorAsociados.f9.setnumero(2);
            GestorAsociados.f9.vaciar();
            GestorAsociados.f9.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablavehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablavehiculosMouseClicked
        row=tablavehiculos.getSelectedRow();
        placa_vehi=tablavehiculos.getValueAt(row, 0).toString();
        modelo_vehi=tablavehiculos.getValueAt(row, 1).toString();
        anio_vehi=tablavehiculos.getValueAt(row, 2).toString();
        dni_chofer=tablavehiculos.getValueAt(row, 3).toString();
        dni_cobra=tablavehiculos.getValueAt(row, 4).toString();
    }//GEN-LAST:event_tablavehiculosMouseClicked

    public void setnumero(int a){
        numero=a;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BoxDistritos;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JTextField campoapellido;
    private javax.swing.JTextField campodireccion;
    private javax.swing.JTextField campodni;
    private javax.swing.JTextField camponombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablavehiculos;
    // End of variables declaration//GEN-END:variables
public String getcampodni(){
    return campodni.getText();
}

public void seter(){
    if(numero==1){
        campodni.setText(Inicio.f3.getcampodni());
        campodni.setEnabled(false);
        camponombre.setText(Inicio.f3.getnombre());
        camponombre.setEnabled(false);
        campoapellido.setText(Inicio.f3.getapellido());
        campoapellido.setEnabled(false);
        campodireccion.setText(Inicio.f3.getdireccion());
        BoxDistritos.setSelectedIndex(Inicio.f3.getdistrito());
        CargarTablaVehiculos("");
    }
    if(numero==2){
        campodni.setText(GestorAsociados.f3.getcampodni());
        campodni.setEnabled(false);
        camponombre.setText(GestorAsociados.f3.getnombre());
        camponombre.setEnabled(false);
        campoapellido.setText(GestorAsociados.f3.getapellido());
        campoapellido.setEnabled(false);
        campodireccion.setText(GestorAsociados.f3.getdireccion());
        BoxDistritos.setSelectedIndex(GestorAsociados.f3.getdistrito());
        CargarTablaVehiculos("");
    }
}

void CargarTablaVehiculos(String valor)
    {
    String[] titulos={"Placa","Tipo","Año","DNI Chofer","DNI Cobrador"};
    String[] registro=new String[5];
    String consultaOracle= "";
    modelo=new MyModel1(null,titulos);
    
    
    ConexionOracle  Oracle=new ConexionOracle();
    Oracle.Conectar();
    //Connection cn=Oracle.Conectar();
    consultaOracle="SELECT PLACA_VEHICULO,MODELO_VEHICULO,ANIO_VEHICULO,DNI_CHOFER,DNI_COBRADOR FROM VEHICULOS"+""
                 + " WHERE DNI_ASOCIADO = '"+campodni.getText()+"'";
       try {
           
//           Statement st=cn.createStatement();
           ResultSet rs=Oracle.getst().executeQuery(consultaOracle);
           while(rs.next())
           {
               registro[0]=rs.getString("PLACA_VEHICULO");
               registro[1]=rs.getString("MODELO_VEHICULO");
               registro[2]=rs.getString("ANIO_VEHICULO");
               registro[3]=rs.getString("DNI_CHOFER");
               registro[4]=rs.getString("DNI_COBRADOR");
               modelo.addRow(registro);
           }
           tablavehiculos.setModel(modelo);
           tablavehiculos.getTableHeader().setReorderingAllowed(false);
       } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
       }
    }

public String getcampoplaca(){
    return placa_vehi;
}
public String getcampomodelo(){
    return modelo_vehi;
}
public String getanio(){
    return anio_vehi;
}
public String getchofer(){
    return dni_chofer;
}
public String getcobra(){
    return dni_cobra;
}


}

class MyModel1 extends DefaultTableModel 
{
   public MyModel1(Object[][] data, Object[] cols) 
   {
      super(data, cols);
   }

   @Override
   public boolean isCellEditable(int row, int col) 
   {
      return false;
   }
}
