/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pregrado
 */
public class EditarVehiculo extends javax.swing.JInternalFrame {
    static Toolkit t = Toolkit.getDefaultToolkit();
    static Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    MyModel2 modelo;
    String dnichofer;
    String dnicobrador;
    String nomchofer;
    String nomcobrador;
    String apechofer;
    String apecobrador;
    int row=-1;
    int numero;
    /**
     * Creates new form EditarVehiculo
     */
    public EditarVehiculo() {
        initComponents();
        this.setPreferredSize(new java.awt.Dimension((screenSize.width)*2/3, screenSize.height));
        PanelEditarVehi.setPreferredSize(new java.awt.Dimension((screenSize.width)*2/3-12, screenSize.height-31));
        //this.setSize((screenSize.width)*2/3-12, screenSize.height-31);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEditarVehi = new javax.swing.JPanel();
        campoplaca = new javax.swing.JTextField();
        campomodelo = new javax.swing.JTextField();
        campoanio = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablachofer = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(540, 400));

        PanelEditarVehi.setBackground(new java.awt.Color(204, 204, 255));
        PanelEditarVehi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 3, true));

        campoplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoplacaActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Cambiar Chofer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("AÑO :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("TIPO DE VEHICULO :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("PLACA :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("EDITAR VEHICULOS");

        tablachofer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablachofer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablachoferMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablachofer);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Cambiar Cobrador");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEditarVehiLayout = new javax.swing.GroupLayout(PanelEditarVehi);
        PanelEditarVehi.setLayout(PanelEditarVehiLayout);
        PanelEditarVehiLayout.setHorizontalGroup(
            PanelEditarVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarVehiLayout.createSequentialGroup()
                .addGroup(PanelEditarVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEditarVehiLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(PanelEditarVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarVehiLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarVehiLayout.createSequentialGroup()
                                .addGroup(PanelEditarVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(65, 65, 65)
                                .addGroup(PanelEditarVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoplaca)
                                    .addComponent(campomodelo)
                                    .addComponent(campoanio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelEditarVehiLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(PanelEditarVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelEditarVehiLayout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(77, 77, 77)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEditarVehiLayout.setVerticalGroup(
            PanelEditarVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarVehiLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(PanelEditarVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PanelEditarVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campomodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PanelEditarVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(PanelEditarVehiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEditarVehi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEditarVehi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoplacaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        if(numero==1){
            Inicio.f7.setnumero(1);
            Inicio.f7.setVisible(true);
            Inicio.f7.CargarTablaVehiculos("");
        }
        if(numero==2){
            GestorAsociados.f7.setnumero(2);
            GestorAsociados.f7.setVisible(true);
            GestorAsociados.f7.CargarTablaVehiculos("");
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(row==-1){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
        }else{
            this.setVisible(false);
            if(numero==1){
                Inicio.f11.setnumero(1);
                Inicio.f11.setVisible(true);
                Inicio.f11.seter();
            }
            if(numero==2){
                GestorAsociados.f11.setnumero(2);
                GestorAsociados.f11.setVisible(true);
                GestorAsociados.f11.seter();
            }
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(row==-1){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
        }else{
            this.setVisible(false);
            if(numero==1){
            Inicio.f12.setnumero(1);
            Inicio.f12.setVisible(true);
            Inicio.f12.seter();
            }
            if(numero==2){
            GestorAsociados.f12.setnumero(2);
            GestorAsociados.f12.setVisible(true);
            GestorAsociados.f12.seter();
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tablachoferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablachoferMouseClicked
        row=tablachofer.getSelectedRow();
        dnichofer=tablachofer.getValueAt(row, 0).toString();
        nomchofer=tablachofer.getValueAt(row, 1).toString();
        apechofer=tablachofer.getValueAt(row, 2).toString();
        dnicobrador=tablachofer.getValueAt(row, 3).toString();
        nomcobrador=tablachofer.getValueAt(row, 4).toString();
        apecobrador=tablachofer.getValueAt(row, 5).toString();;
    }//GEN-LAST:event_tablachoferMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEditarVehi;
    private javax.swing.JTextField campoanio;
    private javax.swing.JTextField campomodelo;
    private javax.swing.JTextField campoplaca;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablachofer;
    // End of variables declaration//GEN-END:variables
public void seter(){
        if(numero==1){
        campoplaca.setText(Inicio.f7.getcampoplaca());
        campoplaca.setEnabled(false);
        campomodelo.setText(Inicio.f7.getcampomodelo());
        campomodelo.setEnabled(false);
        campoanio.setText(Inicio.f7.getanio());
        campoanio.setEnabled(false);
        CargarTablachoferes("");
        }
        if(numero==2){
        campoplaca.setText(GestorAsociados.f7.getcampoplaca());
        campoplaca.setEnabled(false);
        campomodelo.setText(GestorAsociados.f7.getcampomodelo());
        campomodelo.setEnabled(false);
        campoanio.setText(GestorAsociados.f7.getanio());
        campoanio.setEnabled(false);
        CargarTablachoferes("");
        }
}

void CargarTablachoferes(String valor)
    {
    String[] titulos={"DNI Chofer","Nombre Chofer","Apellido Chofer","DNI Cobrador","Nombre Cobrador","Apellido Cobrador"};
    String[] registro=new String[6];
    String a = null,b = null;
    String consultaOracle= "";
    String consultaOracle1= "";
    modelo=new MyModel2(null,titulos);
    
    
    ConexionOracle  Oracle=new ConexionOracle();
    Oracle.Conectar();
    consultaOracle="SELECT DNI_CHOFER,DNI_COBRADOR FROM VEHICULOS"+""
                 + " WHERE PLACA_VEHICULO = '"+campoplaca.getText()+"'";
           try {
           ResultSet rs=Oracle.getst().executeQuery(consultaOracle);
           while(rs.next())
           {
               a=rs.getString("DNI_CHOFER");
               b=rs.getString("DNI_COBRA");
           }
           consultaOracle1="SELECT DNI_CHOFER,NOM_CHOFER,APE_CHOFER,DNI_COBRADOR,NOM_COBRA,APE_COBRADOR FROM CHOFERES, COBRADORES"+""
                 + " WHERE DNI_CHOFER = '"+a+"' AND DNI_COBRADOR = '"+b+"'";
           
           ResultSet rs1=Oracle.getst().executeQuery(consultaOracle1);
           while(rs1.next())
           {
               registro[0]=rs1.getString("DNI_CHOFER");
               registro[1]=rs1.getString("NOM_CHOFER");
               registro[2]=rs1.getString("APE_CHOFER");
               registro[3]=rs1.getString("DNI_COBRADOR");
               registro[4]=rs1.getString("NOM_COBRADOR");
               registro[5]=rs1.getString("APE_COBRADOR");
               modelo.addRow(registro);
           }
           tablachofer.setModel(modelo);
           tablachofer.getTableHeader().setReorderingAllowed(false);
       } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
       }
    }

    public String dnichofer(){
    return dnichofer;
}
    
    public String dnicobrador(){
    return dnicobrador;
}
    public String nomchofer(){
    return nomchofer;
}
    public String nomcobrador(){
    return nomcobrador;
}
    public String apechofer(){
    return apechofer;
}
    public String apecobrador(){
    return apecobrador;
}

    public void setnumero(int a){
        numero=a;
    }
    
}

class MyModel2 extends DefaultTableModel 
{
   public MyModel2(Object[][] data, Object[] cols) 
   {
      super(data, cols);
   }

   @Override
   public boolean isCellEditable(int row, int col) 
   {
      return false;
   }
}
