/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

/**
 *
 * @author Pregrado
 */
public class GestionarAsociado extends javax.swing.JInternalFrame {
    MyModel modelo;
    static Toolkit t = Toolkit.getDefaultToolkit();
    static Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int row=-1;
    String DNI_ASOC;
    String NOM_ASOC;
    String APE_ASOC;
    String DIR_ASOC;
    String DIS_ASOC;
    int numero;
    /**
     * Creates new form GestionarAsociado
     */
    public GestionarAsociado() {
        initComponents();
        this.setPreferredSize(new java.awt.Dimension((screenSize.width)*2/3, screenSize.height));
        PanelGestor.setPreferredSize(new java.awt.Dimension((screenSize.width)*2/3-12, screenSize.height-31));
        CargarTablaAsociados("");
        //AREA.setVisible(false);
    }
    
    void CargarTablaAsociados(String valor)
    {
    String[] titulos={"DNI","Nombres","Apellidos","Direccion","Distrito"};
    String[] registro=new String[5];
    String consultaOracle= "";
    modelo=new MyModel(null,titulos);
    
    
    ConexionOracle  Oracle=new ConexionOracle();
    Oracle.Conectar();
    //Connection cn=Oracle.Conectar();
    consultaOracle="SELECT DNI_ASOCIADO,NOM_ASOCIADO,APE_ASOCIADO,DIR_ASOCIADO,DIS_ASOCIADO FROM ASOCIADOS ";
       try {
           
//           Statement st=cn.createStatement();
           ResultSet rs=Oracle.getst().executeQuery(consultaOracle);
           while(rs.next())
           {
               registro[0]=rs.getString("DNI_ASOCIADO");
               registro[1]=rs.getString("NOM_ASOCIADO");
               registro[2]=rs.getString("APE_ASOCIADO");
               registro[3]=rs.getString("DIR_ASOCIADO");
               registro[4]=rs.getString("DIS_ASOCIADO");
               modelo.addRow(registro);
           }
           TablaAsociados.setModel(modelo);
           TablaAsociados.getTableHeader().setReorderingAllowed(false);
       } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGestor = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAsociados = new javax.swing.JTable();
        LabelTitulo = new javax.swing.JLabel();
        PDF = new javax.swing.JButton();
        AREA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();

        setPreferredSize(new java.awt.Dimension(540, 400));

        PanelGestor.setBackground(new java.awt.Color(204, 204, 255));
        PanelGestor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 3, true));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Modificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TablaAsociados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Apellidos", "Nombres", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaAsociados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAsociadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaAsociados);

        LabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(0, 51, 153));
        LabelTitulo.setText("GESTIÓN DE ASOCIADOS");

        PDF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1448493372_1-02.png"))); // NOI18N
        PDF.setText("Generar Carta Inclusion");
        PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFActionPerformed(evt);
            }
        });

        AREA.setEditable(false);
        AREA.setBackground(new java.awt.Color(204, 204, 255));
        AREA.setColumns(20);
        AREA.setRows(5);
        AREA.setAutoscrolls(false);
        AREA.setBorder(null);

        jScrollPane2.setEnabled(false);
        jScrollPane2.setFocusable(false);

        javax.swing.GroupLayout PanelGestorLayout = new javax.swing.GroupLayout(PanelGestor);
        PanelGestor.setLayout(PanelGestorLayout);
        PanelGestorLayout.setHorizontalGroup(
            PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGestorLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(LabelTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelGestorLayout.createSequentialGroup()
                .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGestorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelGestorLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jButton1)
                                .addGap(94, 94, 94)
                                .addComponent(Modificar)
                                .addGap(96, 96, 96)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelGestorLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(PDF)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelGestorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AREA, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelGestorLayout.setVerticalGroup(
            PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGestorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(LabelTitulo)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Modificar)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(PDF)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelGestorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AREA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        if(row==-1){
            JOptionPane.showMessageDialog(null, "Por favor seleccione un asociado");
        }else{
            this.setVisible(false);
            if(numero==1){
            Inicio.f7.setVisible(true);
            Inicio.f7.setnumero(1);
            Inicio.f7.seter();
            
            }
            if(numero==2){
            GestorAsociados.f7.setVisible(true);
            GestorAsociados.f7.setnumero(2);
            GestorAsociados.f7.seter();
            }
        }
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(numero==1){
        this.setVisible(false);
        Inicio.f2.setnumero(1);
        Inicio.f2.vaciar();
        Inicio.f2.setVisible(true);
        }
        if(numero==2){
        this.setVisible(false);
        GestorAsociados.f2.setnumero(2);
        GestorAsociados.f2.vaciar();
        GestorAsociados.f2.setVisible(true);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TablaAsociadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAsociadosMouseClicked
        row=TablaAsociados.getSelectedRow();
        DNI_ASOC=TablaAsociados.getValueAt(row, 0).toString();
        NOM_ASOC=TablaAsociados.getValueAt(row, 1).toString();
        APE_ASOC=TablaAsociados.getValueAt(row, 2).toString();
        DIR_ASOC=TablaAsociados.getValueAt(row, 3).toString();
        DIS_ASOC=TablaAsociados.getValueAt(row, 4).toString();
    }//GEN-LAST:event_TablaAsociadosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        row=TablaAsociados.getSelectedRow();
        String a ="",b ="";
        String primarykey=TablaAsociados.getValueAt(row, 0).toString();
        ConexionOracle  Oracle=new ConexionOracle();
        Oracle.Conectar();
        //Connection cn=Oracle.Conectar();
        String consultaOracle2="SELECT DNI_CHOFER,DNI_COBRA FROM VEHICULOS"+""
                 + " WHERE DNI_ASOCIADO = '"+primarykey+"'";
        
        
        try{
            FileOutputStream fo = new FileOutputStream("C:\\Users\\RicardoManuél\\Documents\\CB"+TablaAsociados.getValueAt(row, 0).toString()+".pdf");
           Document doc = new Document();
           PdfWriter.getInstance(doc, fo);
           doc.open();
           AREA.append("CARTA DE RETIRO DE LA EMPRESA"); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append("DNI ASOCIADO : "+ DNI_ASOC); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append("NOMBRE ASOCIADO : "+NOM_ASOC); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append("APELLIDO ASOCIADO : "+APE_ASOC); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append("DIRECCION ASOCIADO : "+DIR_ASOC); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append("DISTRITO ASOCIADO : "+DIS_ASOC); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           doc.add(new Paragraph(AREA.getText()));
           doc.close();
           AREA.setText(null);
//           JOptionPane.showMessageDialog(null, "Carta de Inclusion Creada");
            ResultSet rs2=Oracle.getst().executeQuery(consultaOracle2);
            while(rs2.next())
            {
               a=rs2.getString("DNI_CHOFER");
               b=rs2.getString("DNI_COBRA");
            }
            int resp = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar?","ELIMINAR ASOCIADO", JOptionPane.YES_NO_OPTION);
              if(resp==JOptionPane.YES_OPTION){
                String consultaOracle3="DELETE FROM CHOFERES WHERE DNI_CHOFER = '"+a+"'"; 
                String consultaOracle4="DELETE FROM COBRADORES WHERE DNI_COBRA = '"+b+"'"; 
                String consultaOracle="DELETE FROM ASOCIADOS WHERE DNI_ASOCIADO = '"+primarykey+"'";
                String consultaOracle1="DELETE FROM VEHICULOS WHERE DNI_ASOCIADO = '"+primarykey+"'"; 
                ResultSet rs3=Oracle.getst().executeQuery(consultaOracle3);
                ResultSet rs4=Oracle.getst().executeQuery(consultaOracle4);
                ResultSet rs=Oracle.getst().executeQuery(consultaOracle);
                ResultSet rs1=Oracle.getst().executeQuery(consultaOracle1);
                CargarTablaAsociados("");
                JOptionPane.showMessageDialog(this, "Se ha creado la carta de baja vehicular");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFActionPerformed
       try{
           if(row!=-1){
           FileOutputStream fo = new FileOutputStream("C:\\Users\\RicardoManuél\\Documents\\CI"+TablaAsociados.getValueAt(row, 0).toString()+".pdf");
           Document doc = new Document();
           PdfWriter.getInstance(doc, fo);
           doc.open();
           AREA.append("CARTA DE INCLUSION A LA EMPRESA"); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append("DNI ASOCIADO : "+ DNI_ASOC); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append("NOMBRE ASOCIADO : "+NOM_ASOC); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append("APELLIDO ASOCIADO : "+APE_ASOC); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append("DIRECCION ASOCIADO : "+DIR_ASOC); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append("DISTRITO ASOCIADO : "+DIS_ASOC); 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea 
           doc.add(new Paragraph(AREA.getText()));
           doc.close();
           AREA.setText(null);
           JOptionPane.showMessageDialog(this, "Carta de Inclusion Creada");
           }else{
               JOptionPane.showMessageDialog(this, "POR FAVOR SELECCIONE UN ASOCIADO");
           }
               
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_PDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AREA;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton PDF;
    private javax.swing.JPanel PanelGestor;
    private javax.swing.JTable TablaAsociados;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

public String getcampodni(){
//    System.out.println("mi dni " + DNI_ASOC);
    return DNI_ASOC;
}
public String getnombre(){
    return NOM_ASOC;
}
public String getapellido(){
    return APE_ASOC;
}
public String getdireccion(){
    return DIR_ASOC;
}
public int getdistrito(){
    int retorno = 0;
    switch (DIS_ASOC) {
            case "Ancón":  retorno = 0;
                     break;
            case "Ate":  retorno = 1;
                     break;
            case "Barranco":  retorno = 2;
                     break;
            case "Breña":  retorno = 3;
                     break;
            case "Carabayllo":  retorno = 4;
                     break;
            case "Chaclacayo":  retorno = 5;
                     break;
            case "Chorrillos":  retorno = 6;
                     break;
            case "Cieneguilla":  retorno = 7;
                     break;
            case "Comas":  retorno = 8;
                     break;
            case "El Agustino": retorno = 9;
                     break;
            case "Independencia": retorno = 10;
                     break;
            case "Jesús María": retorno = 11;
                     break;
            case "La Molina":  retorno = 12;
                     break;
            case "La Victoria":  retorno = 13;
                     break;
            case "Lince":  retorno = 14;
                     break;
            case "Los Olivos":  retorno = 15;
                     break;
            case "Lurigancho-Chosica":  retorno = 16;
                     break;
            case "Lurin":  retorno = 17;
                     break;
            case "-Magdalena del Mar":  retorno = 18;
                     break;
            case "Pueblo Libre":  retorno = 19;
                     break;
            case "Miraflores":  retorno = 20;
                     break;
            case "Pachacámac": retorno = 21;
                     break;
            case "Pucusana": retorno = 22;
                     break;
            case "Puente Piedra": retorno = 23;
                     break;
            case "Punta Hermosa":  retorno = 24;
                     break;
            case "Punta Negra":  retorno = 25;
                     break;
            case "Rímac":  retorno = 26;
                     break;
            case "San Bartolo":  retorno = 27;
                     break;
            case "San Borja":  retorno = 28;
                     break;
            case "San Isidro":  retorno = 29;
                     break;
            case "San Juan de Lurigancho":  retorno = 30;
                     break;
            case "San Juan de Miraflores":  retorno = 31;
                     break;
            case "San Luis":  retorno = 32;
                     break;
            case "San Martín de Porres": retorno = 33;
                     break;
            case "San Miguel": retorno = 34;
                     break;
            case "Santa Anita": retorno = 35;
                     break;
            case "Santa María del Mar":  retorno = 36;
                     break;
            case "Santa Rosa":  retorno = 37;
                     break;
            case "Santiago de Surco":  retorno = 38;
                     break;
            case "Surquillo":  retorno = 39;
                     break;
            case "Villa El Salvador":  retorno = 40;
                     break;
            case "Villa María del Triunfo":  retorno = 41;
                     break;
        }
    
    return retorno;
}

public void setnumero(int a){
        numero=a;
    }

}

class MyModel extends DefaultTableModel 
{
   public MyModel(Object[][] data, Object[] cols) 
   {
      super(data, cols);
   }

   public boolean isCellEditable(int row, int col) 
   {
      return false;
   }
   
}
