/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RicardoManuél
 */
public class RegistraSancion extends javax.swing.JInternalFrame {
    MyModel6 modelo;
    int row=-1;
    /**
     * Creates new form RegistrarQueja
     */
    public RegistraSancion() {
        initComponents();
        CargarTablaVehiculos("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AREA = new javax.swing.JTextArea();
        PanelGestor = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BoxEstado = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        campoplaca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BoxDias = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablavehiculos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        LabelTitulo1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        motivo = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PDF = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();

        AREA.setColumns(20);
        AREA.setRows(5);

        PanelGestor.setBackground(new java.awt.Color(204, 204, 255));
        PanelGestor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 3, true));

        LabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(0, 51, 153));
        LabelTitulo.setText("TABLA DE VEHICULOS SANCIONADOS");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ESTADO DEL VEHICULO:");

        BoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Habilitado", "Deshabilitado" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("PLACA :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("NUMERO DE DIAS :");

        BoxDias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", " " }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Cambiar Estado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablavehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablavehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablavehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablavehiculos);

        LabelTitulo1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LabelTitulo1.setForeground(new java.awt.Color(0, 51, 153));
        LabelTitulo1.setText("GESTIONAR SANCIONES");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("MOTIVO :");

        motivo.setColumns(20);
        motivo.setRows(5);
        jScrollPane2.setViewportView(motivo);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Registrar Queja");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        PDF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1448493372_1-02.png"))); // NOI18N
        PDF.setText("Generar Reporte");
        PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGestorLayout = new javax.swing.GroupLayout(PanelGestor);
        PanelGestor.setLayout(PanelGestorLayout);
        PanelGestorLayout.setHorizontalGroup(
            PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanelGestorLayout.createSequentialGroup()
                .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGestorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGestorLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(76, 76, 76)
                        .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BoxEstado, 0, 141, Short.MAX_VALUE)
                            .addComponent(BoxDias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelGestorLayout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelGestorLayout.createSequentialGroup()
                                    .addGap(161, 161, 161)
                                    .addComponent(jButton1))
                                .addGroup(PanelGestorLayout.createSequentialGroup()
                                    .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(65, 65, 65)
                                    .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(campoplaca, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addComponent(jButton2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelGestorLayout.createSequentialGroup()
                            .addGap(236, 236, 236)
                            .addComponent(LabelTitulo1))))
                .addContainerGap(64, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addGroup(PanelGestorLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(LabelTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGestorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(PDF)
                .addGap(249, 249, 249))
        );
        PanelGestorLayout.setVerticalGroup(
            PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGestorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitulo1)
                .addGap(18, 18, 18)
                .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGestorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGestorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(BoxDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGestorLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGestorLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(PDF)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGestor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
                        ConexionOracle  Oracle=new ConexionOracle();
                        Oracle.Conectar();
                        String consultaOracle = "UPDATE VEHICULOS SET ESTADO_VEHICULO = '"+BoxEstado.getSelectedItem().toString()+
                                "',DSAN_VEHICULO= '"+BoxDias.getSelectedItem().toString()+"' WHERE PLACA_VEHICULO = '"+
                                campoplaca.getText()+"'";
                        //System.out.println(consultaOracle);
                        Oracle.getst().execute(consultaOracle);
                        Oracle.getConexion().close();
                        JOptionPane.showMessageDialog(this, "Sancion Registrada");
                        CargarTablaVehiculos("");
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Error Ingresando Datos - Codigo : "+e);
                    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablavehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablavehiculosMouseClicked
        row=tablavehiculos.getSelectedRow();
        motivo.setText(null);
        cargarcampo(tablavehiculos.getValueAt(row, 0).toString());
        campoplaca.setText(tablavehiculos.getValueAt(row, 0).toString());
        if(tablavehiculos.getValueAt(row, 3).toString().equals("Habilitado")){
            BoxEstado.setSelectedIndex(0);
        }else{
            BoxEstado.setSelectedIndex(1);
        }
        String dias = tablavehiculos.getValueAt(row, 4).toString();
        switch(dias){
            case "0": BoxDias.setSelectedIndex(0);
                      break;
            case "1": BoxDias.setSelectedIndex(1);
                      break;
            case "2": BoxDias.setSelectedIndex(2);
                      break;
            case "3": BoxDias.setSelectedIndex(3);
                      break;
            case "4": BoxDias.setSelectedIndex(4);
                      break;
            case "5": BoxDias.setSelectedIndex(5);
                      break;    
            case "6": BoxDias.setSelectedIndex(6);
                      break;    
            case "7": BoxDias.setSelectedIndex(7);
                      break;    
            
        }
        
    }//GEN-LAST:event_tablavehiculosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
                        ConexionOracle  Oracle=new ConexionOracle();
                        Oracle.Conectar();
                        String consultaOracle = "INSERT INTO QUEJAS(QUEJA_VEHI,PLACA_VEHI) VALUES ('"+motivo.getText()+
                                "','"+campoplaca.getText()+"')";
                        Oracle.getst().execute(consultaOracle);
                        Oracle.getConexion().close();
                        JOptionPane.showMessageDialog(this, "Sancion Registrada");
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Error Ingresando Datos - Codigo : "+e);
                    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        motivo.setText(null);
        ConexionOracle  Oracle=new ConexionOracle();
        Oracle.Conectar();
        String texto="";
        String consultaOracle="SELECT QUEJA_VEHICULO FROM QUEJAS WHERE PLACA_VEHICULO = '"+campoplaca.getText()+"'";
        try {
           
//           Statement st=cn.createStatement();
           ResultSet rs=Oracle.getst().executeQuery(consultaOracle);
           while(rs.next())
           {
               texto=rs.getString("QUEJA_VEHICULO");
           }
           motivo.append(texto);
       } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFActionPerformed
        try{
            if(row!=-1){
                FileOutputStream fo = new FileOutputStream("C:\\Users\\RicardoManuél\\Documents\\SAN"+tablavehiculos.getValueAt(row, 0).toString()+".pdf");
                Document doc = new Document();
                PdfWriter.getInstance(doc, fo);
                doc.open();
                AREA.append("REPORTE DE SANSION");
                AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea
                AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea
                String total ="PLACA : "+tablavehiculos.getValueAt(row, 0).toString()+"DNI CHOFER : "+tablavehiculos.getValueAt(row, 5).toString()+"DNI COBRADOR : "+tablavehiculos.getValueAt(row, 6).toString();
                AREA.append(total);
                AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea
                AREA.append("POR MOTIVO");
                AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea
                AREA.append(motivo.getText());
                AREA.append(System.getProperty("line.separator")); // Esto para el salto de línea
                AREA.append("POR "+tablavehiculos.getValueAt(row, 4).toString()+" DIAS");
                doc.add(new Paragraph(AREA.getText()));
                doc.close();
                AREA.setText(null);
                JOptionPane.showMessageDialog(this, "REPORTE DE SANCION CREADO");
            }else{
                JOptionPane.showMessageDialog(this, "POR FAVOR SELECCIONE UN VEHICULO");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_PDFActionPerformed

    public void cargarcampo(String Placa){
        ConexionOracle  Oracle=new ConexionOracle();
        Oracle.Conectar();
        String texto="";
        String consultaOracle="SELECT QUEJA_VEHICULO FROM QUEJAS WHERE PLACA_VEHICULO = '"+Placa+"'";
        try {
           
//           Statement st=cn.createStatement();
           ResultSet rs=Oracle.getst().executeQuery(consultaOracle);
           while(rs.next())
           {
               texto=rs.getString("QUEJA_VEHICULO");
           }
           motivo.append(texto);
       } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
       }
    }
    
    void CargarTablaVehiculos(String valor)
    {
    String[] titulos={"Placa","Modelo","Año","Estado Vehiculo","Dias de Sancion","DNI Chofer","DNI Cobrador"};
    String[] registro=new String[7];
    String consultaOracle= "";
    modelo=new MyModel6(null,titulos);
    
    
    ConexionOracle  Oracle=new ConexionOracle();
    Oracle.Conectar();
    //Connection cn=Oracle.Conectar();
    consultaOracle="SELECT PLACA_VEHICULO,MODELO_VEHICULO,ANIO_VEHICULO,ESTADO_VEHICULO,DSAN_VEHICULO,DNI_CHOFER,DNI_COBRADOR FROM VEHICULOS"+""
                 + " WHERE ESTADO_VEHICULO = 'Deshabilitado'";
       try {
           
//           Statement st=cn.createStatement();
           ResultSet rs=Oracle.getst().executeQuery(consultaOracle);
           while(rs.next())
           {
               registro[0]=rs.getString("PLACA_VEHICULO");
               registro[1]=rs.getString("MODELO_VEHICULO");
               registro[2]=rs.getString("ANIO_VEHICULO");
               registro[3]=rs.getString("ESTADO_VEHICULO");
               registro[4]=rs.getString("DSAN_VEHICULO");
               registro[5]=rs.getString("DNI_CHOFER");
               registro[6]=rs.getString("DNI_COBRADOR");
               modelo.addRow(registro);
           }
           tablavehiculos.setModel(modelo);
           tablavehiculos.getTableHeader().setReorderingAllowed(false);
       } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AREA;
    private javax.swing.JComboBox BoxDias;
    private javax.swing.JComboBox BoxEstado;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelTitulo1;
    private javax.swing.JButton PDF;
    private javax.swing.JPanel PanelGestor;
    private javax.swing.JTextField campoplaca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea motivo;
    private javax.swing.JTable tablavehiculos;
    // End of variables declaration//GEN-END:variables
}

class MyModel6 extends DefaultTableModel 
{
   public MyModel6(Object[][] data, Object[] cols) 
   {
      super(data, cols);
   }

   @Override
   public boolean isCellEditable(int row, int col) 
   {
      return false;
   }
}