package Modelo;
// Generated 27/05/2016 04:09:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Choferes generated by hbm2java
 */
public class Choferes  implements java.io.Serializable {


     private String dniChofer;
     private String nomChofer;
     private String apeChofer;
     private Set vehiculoses = new HashSet(0);

    public Choferes() {
    }

	
    public Choferes(String dniChofer, String nomChofer, String apeChofer) {
        this.dniChofer = dniChofer;
        this.nomChofer = nomChofer;
        this.apeChofer = apeChofer;
    }
    public Choferes(String dniChofer, String nomChofer, String apeChofer, Set vehiculoses) {
       this.dniChofer = dniChofer;
       this.nomChofer = nomChofer;
       this.apeChofer = apeChofer;
       this.vehiculoses = vehiculoses;
    }
   
    public String getDniChofer() {
        return this.dniChofer;
    }
    
    public void setDniChofer(String dniChofer) {
        this.dniChofer = dniChofer;
    }
    public String getNomChofer() {
        return this.nomChofer;
    }
    
    public void setNomChofer(String nomChofer) {
        this.nomChofer = nomChofer;
    }
    public String getApeChofer() {
        return this.apeChofer;
    }
    
    public void setApeChofer(String apeChofer) {
        this.apeChofer = apeChofer;
    }
    public Set getVehiculoses() {
        return this.vehiculoses;
    }
    
    public void setVehiculoses(Set vehiculoses) {
        this.vehiculoses = vehiculoses;
    }




}


