package Modelo;
// Generated 27/05/2016 04:09:36 PM by Hibernate Tools 4.3.1



/**
 * Salidas generated by hbm2java
 */
public class Salidas  implements java.io.Serializable {


     private String idSalida;
     private Vehiculos vehiculos;
     private String horaSalida;
     private String fechaSalida;

    public Salidas() {
    }

    public Salidas(String idSalida, Vehiculos vehiculos, String horaSalida, String fechaSalida) {
       this.idSalida = idSalida;
       this.vehiculos = vehiculos;
       this.horaSalida = horaSalida;
       this.fechaSalida = fechaSalida;
    }
   
    public String getIdSalida() {
        return this.idSalida;
    }
    
    public void setIdSalida(String idSalida) {
        this.idSalida = idSalida;
    }
    public Vehiculos getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Vehiculos vehiculos) {
        this.vehiculos = vehiculos;
    }
    public String getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(String horaSalida) {
        this.horaSalida = horaSalida;
    }
    public String getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(String fechaSalida) {
        this.fechaSalida = fechaSalida;
    }




}


