package Modelo;
// Generated 27/05/2016 04:09:36 PM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String idUser;
     private String passUser;
     private String tipoUser;

    public Usuarios() {
    }

    public Usuarios(String idUser, String passUser, String tipoUser) {
       this.idUser = idUser;
       this.passUser = passUser;
       this.tipoUser = tipoUser;
    }
   
    public String getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }
    public String getPassUser() {
        return this.passUser;
    }
    
    public void setPassUser(String passUser) {
        this.passUser = passUser;
    }
    public String getTipoUser() {
        return this.tipoUser;
    }
    
    public void setTipoUser(String tipoUser) {
        this.tipoUser = tipoUser;
    }




}


